# version: "3"

services:
  django:
    image: ghcr.io/ubuntu-kr/ubuntu-kr-qr-kiosk-admin:a73f5bf57fbb9577690c502a2b9c325c9bf62958
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    ports:
      - 8000:8000
    environment:
      - DB_NAME=kiosk
      - DB_USER=kioskuser
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file: "docker-compose.env"
    depends_on:
      - redis
      - postgres
  worker:
    image: ghcr.io/ubuntu-kr/ubuntu-kr-qr-kiosk-admin:a73f5bf57fbb9577690c502a2b9c325c9bf62958
    command: celery -A kioskadmin worker -l INFO
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    environment:
      - DB_NAME=kiosk
      - DB_USER=kioskuser
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file: "docker-compose.env"
    depends_on:
      - redis
      - postgres
      - django
  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=kioskuser
      - POSTGRES_DB=kiosk
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file: "docker-compose.env"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
  caddy:
    image: caddy
    volumes:
      - ./data/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
      - ./static:/var/www/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
